### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by ethicnology** [ilap/slip39-dart#1]
Hi, I tried to upgrade pointycastle and add null safety to your package using dart migration tool, it result with tons of errors.

Would you accept to upgrade your package to null safety ?

**Comment by ilap** [comment]
Hi,

Oooh, sorry I completely forgotten this package. I am going to update to to use pinenacl dart instead of pointycastle and migrate to null safety.

I will see how it goes.

Cheers,

Pal

**Comment by ilap** [comment]
Done. use v0.2.0 from pub.dev or clone the master.

Cheers,

Pal
