### ISSUE TITLE
The length of the master secret in bytes must be an even number.

### ISSUE THREAD

**Issue by ludovn** [ilap/slip39-dart#2]
I generate seed phrase 12 and 24 words using bip39 and use your library to split shares, but i always meet this issue
`The length of the master secret in bytes must be an even number.`

> package:slip39/src/slip39.dart 221:7                    Slip39._validateParams
package:slip39/src/slip39.dart 44:12                    new Slip39.from

Is there any information about it, thank you so much!

**Comment by ilap** [comment]
Hi, 

You should use the seed (the 64 byte long key 32+32) or the 128 or 256-bit, based on your 12, 24 mnemonics, entropies, but not the mnemonic itself.
- Seed: 64 long hexa string: **OK**
- Mnemonic: 12 or 24 words: **NOT OK**
- Masterkey: is a bech32 string like "xprv....." **NOT OK**
- Entropies: Between 16 and 32 bytes long hexa strings **OK**

**Comment by ludovn** [comment]
Hi, thank you for your response, i will use entropy and split entropy.
